[package]
name = "jiffs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_norway = "0.9"
json-patch = "4.1.0"
jsonptr = "0.7.1"

[dev-dependencies]
tempfile = "3.8"
